/**
 * Copyright (C) 2012 Tomas Shestakov.
 */

package cache;

/**
 * Factory of some objects generated by some key.
 * @param <K> type of the key
 * @param <V> type of the value
 */
public interface ObjectFactory<K, V> {

    /**
     * @return some object by specified key or null if object not exists.
     */
    V getObject(K key);
}
